# Site settings
title: SVNCRWNS
email: hello@svncrwns.com
description: > # this means to ignore newlines until "baseurl:"
  SVNCRWNS is a management company + studio. We use our skills and resources to work with clients to push their missions forward.  Services include Creative Direction, Strategy, Image Making and Web Design + Development
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.svncrwns.com" # the base hostname & protocol for your site
port: 4000

include: ["_pages"]

# Build settings
markdown: kramdown

# Site Variables
logo: "/dist/images/svn-logo.svg"
theme2020-logo: "/dist/images/crwns-logo-graphic-b.png"
facebook: https://www.facebook.com/svncrwns
instagram: https://www.instagram.com/svncrwns
capabilities-doc: http://www.svncrwns.com/SVNCRWNS2021SERVICES.pdf
scheduling-link: https://calendly.com/svncrwns/svncrwns-sessions?month=2020-10

# Brand Colors
homepage-bg-color: '#f7f7f7'

plugins:
- jekyll-menus